import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils/utils";

const NunitoFont = Outfit({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-nunito",
});

export const metadata: Metadata = {
    title: "ShuleYetu",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "font-NunitoFont antialiased",
                    NunitoFont.variable
                )}
            >
                {children}
            </body>
        </html>
    );
}
